export enum REQUEST_SAVER {
  // TODO
  TODO_FETCH_LIST_REQUEST = 'TODO_FETCH_LIST_REQUEST',
  TODO_FETCH_DETAIL_REQUEST = 'TODO_FETCH_DETAIL_REQUEST',
  TODO_CREATE_REQUEST = 'TODO_CREATE_REQUEST',
  TODO_UPDATE_REQUEST = 'TODO_UPDATE_REQUEST',
  TODO_DELETE_REQUEST = 'TODO_DELETE_REQUEST'
}
